# Choose whatever you want, version >= 1.16
FROM golang:1.19-alpine

WORKDIR /app

RUN go env -w GOPROXY=https://goproxy.cn,direct && \
    go install github.com/cosmtrek/air@latest   && \
    # the wget url is the package in my OBS, the origin url is: https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
    wget https://lanpesk-package-proxy.obs.cn-north-4.myhuaweicloud.com/ffmpeg-release-amd64-static.tar.xz && \
    tar -xvJf ffmpeg-release-amd64-static.tar.xz -C /tmp && \
    rm -f ffmpeg-release-amd64-static.tar.xz && \
    # a soft link for ffmpeg, the ffmpeg dir name maybe different, if you use ffmpeg in other version, please check this
    ln -s /tmp/ffmpeg-5.1.1-amd64-static/ffmpeg /usr/bin/ffmpeg

COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.toml"]