version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_air
    depends_on:
      - redis
      - postgres
    ports:
      - 8080:8080
    command: sh -c "air"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - DB_HOST=postgres
      - DB_USER=tiktok
      - DB_PASSWD=secret
      - DB_NAME=tiktok
      - RDB_HOST=redis
      - Host=http://47.113.179.123:8080

  postgres:
    build: 
      context: .
      dockerfile: Dockerfile_postgre
    depends_on:
      - redis
    volumes:
      - tiktok-go-pg-data:/var/lib/postgresql/data
      - ./repository/sql:/tmp
    environment:
      - POSTGRES_USER=tiktok
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=tiktok
  
  redis:
    image: redis:latest

volumes:
  tiktok-go-pg-data:
